services:
  cpu:
    container_name: project_name.cpu
    build:
      context: .
      dockerfile: docker/Dockerfile.cpu
    shm_size: '64gb'
    volumes:
      - type: bind
        source: $PWD
        target: /workspace
      - type: volume
        source: venv
        target: /workspace/.venv
    working_dir: /workspace
    tty: true
  gpu:
    container_name: project_name.gpu
    build:
      context: .
      dockerfile: docker/Dockerfile.gpu
    shm_size: '64gb'
    volumes:
      - type: bind
        source: $PWD
        target: /workspace
      - type: volume
        source: venv
        target: /workspace/.venv
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    tty: true

volumes:
  venv:
